from app.models.audit_log import AuditLog
from app.models.candidate import Candidate
from app.models.criterion import Criterion
from app.models.criterion_score import CriterionScore
from app.models.collaboration import (
    AccesClient,
    EchangeClient,
    EtapeMandat,
    MessageEnvoye,
    ModeleDocument,
    Rapport,
    nouveau_jeton,
)
from app.models.enums import (
    AnalysisStatus,
    AuteurEchange,
    CandidateSource,
    EtatEtape,
    HrStatus,
    Language,
    Provenance,
    Recommendation,
    SessionStatus,
    SourceCandidature,
    StatutAvis,
    StatutCandidature,
    StatutEnvoi,
    StatutMandat,
    StatutRapport,
    TypeEchange,
    UsageModele,
    UserRole,
)
from app.models.recruitment_session import RecruitmentSession, new_public_key
from app.models.recrutement import (
    Avis,
    Candidat,
    Candidature,
    Client,
    DiplomeCandidat,
    Elimination,
    Entretien,
    ExperienceCandidat,
    LigneEntretien,
    LigneNotation,
    Mandat,
    Notation,
    PieceCandidature,
    Poste,
    nouvelle_cle_publique,
)
from app.models.user import User

# Effet de bord : enregistre la table `parametre` dans les metadata.
from app.services.parametres import Parametre  # noqa: E402,F401

__all__ = [
    "AccesClient",
    "AnalysisStatus",
    "AuditLog",
    "AuteurEchange",
    "Avis",
    "Candidat",
    "Candidate",
    "CandidateSource",
    "Candidature",
    "Client",
    "Criterion",
    "CriterionScore",
    "DiplomeCandidat",
    "EchangeClient",
    "Elimination",
    "EtapeMandat",
    "EtatEtape",
    "Entretien",
    "ExperienceCandidat",
    "HrStatus",
    "Language",
    "LigneNotation",
    "Mandat",
    "LigneEntretien",
    "MessageEnvoye",
    "ModeleDocument",
    "Notation",
    "PieceCandidature",
    "Poste",
    "Provenance",
    "Rapport",
    "RecruitmentSession",
    "Recommendation",
    "SessionStatus",
    "SourceCandidature",
    "StatutAvis",
    "StatutCandidature",
    "StatutEnvoi",
    "StatutMandat",
    "StatutRapport",
    "TypeEchange",
    "UsageModele",
    "Parametre",
    "User",
    "UserRole",
    "new_public_key",
    "nouveau_jeton",
    "nouvelle_cle_publique",
]
