"""Coeur métier de la présélection.

Entièrement déterministe et hors-ligne : ni base de données, ni réseau, ni
modèle de langage. Tout ce qui décide du sort d'une candidature vit ici, et
peut donc être relu, testé et défendu ligne à ligne.
"""

from app.domain.bareme import (
    BAREME_ENTRETIEN,
    BAREME_PAR_DEFAUT,
    TOTAL_ENTRETIEN,
    Bareme,
    BaremeConsistance,
    BaremeExperience,
    BaremeFormation,
    Classement,
    DecisionSeuil,
    LigneEntretien,
    LigneNote,
    Notation,
    NoteEntretien,
    NoteFinale,
    Qualification,
    RegleAjout,
    appliquer_seuil,
    classer,
    grille_entretien_depuis_liste,
    grille_entretien_vers_liste,
    note_de_conformite,
    note_finale,
    noter,
    qualifier,
    sections_entretien,
    valider_grille_entretien,
)
from app.domain.eligibilite import Elimination, est_eligible, evaluer_eligibilite
from app.domain.profil import (
    SANS_RESTRICTION,
    Diplome,
    GroupePieces,
    Experience,
    ExigenceSpecifique,
    ExigencesPoste,
    ProfilCandidat,
    RestrictionPoste,
    duree_mois,
    fusionner_intervalles,
)
from app.domain.referentiel import (
    DOSSIER_STANDARD,
    CodeAjout,
    MotifElimination,
    NiveauDiplome,
    PieceDossier,
    Sexe,
    TypeAvis,
    normaliser_domaine,
)

__all__ = [
    "BAREME_ENTRETIEN",
    "BAREME_PAR_DEFAUT",
    "DOSSIER_STANDARD",
    "SANS_RESTRICTION",
    "TOTAL_ENTRETIEN",
    "Bareme",
    "BaremeConsistance",
    "BaremeExperience",
    "BaremeFormation",
    "Classement",
    "CodeAjout",
    "DecisionSeuil",
    "Diplome",
    "Elimination",
    "ExigenceSpecifique",
    "ExigencesPoste",
    "GroupePieces",
    "Experience",
    "LigneEntretien",
    "LigneNote",
    "MotifElimination",
    "Notation",
    "NoteEntretien",
    "NoteFinale",
    "Qualification",
    "NiveauDiplome",
    "PieceDossier",
    "ProfilCandidat",
    "RegleAjout",
    "RestrictionPoste",
    "Sexe",
    "TypeAvis",
    "appliquer_seuil",
    "classer",
    "duree_mois",
    "est_eligible",
    "evaluer_eligibilite",
    "fusionner_intervalles",
    "grille_entretien_depuis_liste",
    "grille_entretien_vers_liste",
    "normaliser_domaine",
    "note_de_conformite",
    "note_finale",
    "noter",
    "qualifier",
    "sections_entretien",
    "valider_grille_entretien",
]
